### ISSUE TITLE
After updating to v0.5.0 excluding files no longer works

### ISSUE THREAD

**Issue by joebailey26** [netlify-labs/netlify-plugin-sitemap#28]
I have tried a combination of different exclusion methods: 
```
exclude = [
      'dist/404.html',
      'dist/404/',
      './dist/404.html',
      './dist/404/'
    ]
```
And tried setting the build directory to both ```dist``` and ```.dist``` 

However the 404 page is still showing up in the sitemap.

This is the rest of my configuration:
```
    prettyURLs = true
    trailingSlash = true
```

**Comment by erezrokah** [comment]
Hi @joebailey26, can you please share a repo reproducing the issue? If not can you share your full `netlify.toml` and `dist` directory structure?

**Comment by joebailey26** [comment]
Here is my repo: https://github.com/Galexia-Agency/Website where I am experiencing the issue.

**Comment by tpett** [comment]
I'm having the same issue. This is the line that broke it:

https://github.com/netlify-labs/netlify-plugin-sitemap/compare/v0.3.4...v0.5.0#diff-168726dbe96b3ce427e7fedce31bb0bcR10

Previously, you were using a relative path for `buildPath` and after 0.3.4 that is now a full absolute directory. This makes the exclude patterns not work unless they are prefixed with a `**` because we will never know the exact absolute path in all circumstances. 

Prefixing each exclude with `**` is a potential workaround, but it is definitely dangerous and not equivalent to the old behavior.

**Comment by colinrim** [comment]
same here, for some reason /404/ page is being listed within the sitemap even tho excluded as such:
```
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "public"
  changeFreq = "daily"
  prettyURLs = true
  trailingSlash = true
  exclude = [
    '**/404/',
    '**/**/404/',
    './public/404/',
    './public/404',
```
any ideas?
